protocol imap {
  mail_plugins = imap_sieve
}

sieve_plugins = sieve_imapsieve sieve_extprograms
sieve_pipe_bin_dir = /usr/lib/dovecot/sieve-pipe

sieve_global_extensions {
  vnd.dovecot.pipe = yes
  vnd.dovecot.environment = yes
}

# Spam learning
## When to Spam
mailbox Spam {
  sieve_script report-spam {
    type = before
    cause = copy append
    path = /etc/dovecot/sieve/report-spam.sieve
  }
}

## When to Junk
mailbox Junk {
  sieve_script report-spam-junk {
    type = before
    cause = copy append
    path = /etc/dovecot/sieve/report-spam.sieve
  }
}

# Ham learning
## When from Spam
imapsieve_from Spam {
  sieve_script report-ham-spam {
    type = before
    cause = copy append
    path = /etc/dovecot/sieve/report-ham.sieve
  }
}

## When from Junk
imapsieve_from Junk {
  sieve_script report-ham-junk {
    type = before
    cause = copy append
    path = /etc/dovecot/sieve/report-ham.sieve
  }
}
