#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# SPECIFIC SETTERS
#=================================================

set__password() {
    if [ ! "$password" == "" ]
    then
        ynh_print_info --message="Saving the new password in the Rspamd configuration..."
        HASH=$(rspamadm pw -p "$password")
        echo "password = \"$HASH\"" > /etc/rspamd/local.d/worker-controller.inc
    fi
}

ynh_app_config_run "$1"
