#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__password() {
    if [ ! "$password" == "" ]
    then
        ynh_app_setting_set --app=$app --key=password --value="$password"
    fi
}

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_app_config_apply() {
    _ynh_app_config_apply
    
    if [ "${changed[password]}" == "true" ] && [ ! "$password" == "" ]
    then
        HASH=$(rspamadm pw -p $password)
        echo "password = \"$HASH\"" > "/etc/rspamd/local.d/worker-controller.inc"
        ynh_systemctl --service=rspamd --action="restart"
    fi
}

ynh_app_config_run $1
