#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

# Add rspamd conf
## Add redis conf
ynh_config_add --template="rspamd_redis.conf" --destination="/etc/rspamd/local.d/redis.conf"

## Add per-user conf
ynh_config_add --template="rspamd_classifier-bayes.conf" --destination="/etc/rspamd/local.d/classifier-bayes.conf"

## Set web interface password
HASH=$(rspamadm pw -p "$password")
echo "password = \"$HASH\"" > /etc/rspamd/local.d/worker-controller.inc
ynh_print_info --message="Please note the password for the web interface: $password"

## Set permissions
chmod 644 /etc/rspamd/local.d/*

## Integrate rspamd in YunoHost service list
yunohost service add "$app" --description="Spam filtering system"

## Restart rspamd to load the new conf
ynh_systemctl --service=rspamd --action="restart"

# Add postfix configuration hook and regen postfix conf
ynh_config_add --template="yunohost_postfix_regenconf_hook" --destination="/usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd"
yunohost tools regen-conf postfix
ynh_systemctl --service=postfix --action="restart"

# Add dovecot conf
## Create sieve directories
mkdir -p /etc/dovecot/global_script
mkdir -p /usr/lib/dovecot/sieve-pipe

## Add the config file for spam handling
if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
    ynh_config_add --template="dovecot_rspamd-learning_bookworm.conf" --destination="/etc/dovecot/yunohost.d/post-ext.d/rspamd-learning.conf"
elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
    ynh_config_add --template="dovecot_rspamd-learning_trixie.conf" --destination="/etc/dovecot/yunohost.d/post-ext.d/rspamd-learning.conf"
fi

## Restart dovecot to load the new conf
ynh_systemctl --service=dovecot --action="restart"

## Add the sieve script to move Spam mails to the user's Junk folder
ynh_config_add --template="dovecot_rspamd-spam-to-junk-folder.sieve" --destination="/etc/dovecot/global_script/rspamd-spam-to-junk-folder.sieve"

## Deploy imap_sieve scripts for spam/ham learning
### Spam learning
ynh_config_add --template="dovecot_rspamd-report-spam.sieve" --destination="/etc/dovecot/global_script/rspamd-report-spam.sieve"
ynh_config_add --template="dovecot_rspamd-learn-spam.sh" --destination="/usr/lib/dovecot/sieve-pipe/rspamd-learn-spam.sh"

### Ham learning
ynh_config_add --template="dovecot_rspamd-report-ham.sieve" --destination="/etc/dovecot/global_script/rspamd-report-ham.sieve"
ynh_config_add --template="dovecot_rspamd-learn-ham.sh" --destination="/usr/lib/dovecot/sieve-pipe/rspamd-learn-ham.sh"

## Set permissions
chmod 750 /etc/dovecot/global_script/*.sieve
chmod 755 /usr/lib/dovecot/sieve-pipe/rspamd-learn-*.sh

## Restart dovecot to load the new sieve scripts
ynh_systemctl --service=dovecot --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
