#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

# Add rspamd conf
## Add redis conf
ynh_config_add --template="rspamd_redis.conf" --destination="/etc/rspamd/local.d/redis.conf"

## Add per-user conf
ynh_config_add --template="rspamd_classifier-bayes.conf" --destination="/etc/rspamd/local.d/classifier-bayes.conf"

## Set web interface password
HASH=$(rspamadm pw -p $password)
echo "password = \"$HASH\"" > "/etc/rspamd/local.d/worker-controller.inc"
echo "Please note the password for the web interface: $password"

## Set permissions
chmod 644 /etc/rspamd/local.d/redis.conf /etc/rspamd/local.d/classifier-bayes.conf /etc/rspamd/local.d/worker-controller.inc

## Integrate rspamd in YunoHost service list
yunohost service add "$app" --description="Spam filtering system"

## Restart rspamd to load the new conf
ynh_systemctl --service=rspamd --action="restart"

# Add postfix configuration hook and regen postfix conf
ynh_config_add --template="yunohost_postfix_regenconf_hook" --destination="/usr/share/yunohost/hooks/conf_regen/99-postfix_rspamd"
yunohost tools regen-conf postfix
ynh_systemctl --service=postfix --action="restart"

# Add dovecot conf
## Create sieve directories
mkdir -p "/etc/dovecot/sieve"
mkdir -p "/usr/lib/dovecot/sieve-pipe"

## Add the config file for spam handling
if [[ $YNH_DEBIAN_VERSION == "bookworm" ]]; then
    ynh_config_add --template="dovecot_antispam_bookworm.conf" --destination="/etc/dovecot/yunohost.d/post-ext.d/antispam.conf"
elif [[ $YNH_DEBIAN_VERSION == "trixie" ]]; then
    ynh_config_add --template="dovecot_antispam_trixie.conf" --destination="/etc/dovecot/yunohost.d/post-ext.d/antispam.conf"
fi

## Restart dovecot to load the new conf
ynh_systemctl --service=dovecot --action="restart"

## Add the sieve script to move Spam mails to the user's Junk folder
ynh_config_add --template="dovecot_spam-to-junk-folder.sieve" --destination="/etc/dovecot/sieve/spam-to-junk-folder.sieve"

## Deploy imap_sieve scripts for spam/ham learning
### Spam learning
ynh_config_add --template="dovecot_report-spam.sieve" --destination="/etc/dovecot/sieve/report-spam.sieve"
ynh_config_add --template="dovecot_rspamd-learn-spam.sh" --destination="/usr/lib/dovecot/sieve-pipe/rspamd-learn-spam.sh"

### Ham learning
ynh_config_add --template="dovecot_report-ham.sieve" --destination="/etc/dovecot/sieve/report-ham.sieve"
ynh_config_add --template="dovecot_rspamd-learn-ham.sh" --destination="/usr/lib/dovecot/sieve-pipe/rspamd-learn-ham.sh"

## Compile sieve scripts
sievec "/etc/dovecot/sieve/spam-to-junk-folder.sieve"
sievec "/etc/dovecot/sieve/report-spam.sieve"
sievec "/etc/dovecot/sieve/report-ham.sieve"

## Set permissions
chmod 755 "/etc/dovecot/sieve"
chmod 644 /etc/dovecot/sieve/report-*.sieve /etc/dovecot/sieve/report-*.svbin
chmod 755 /usr/lib/dovecot/sieve-pipe/rspamd-learn-*.sh

## Restart dovecot to load the new sieve scripts
ynh_systemctl --service=dovecot --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
